---
- name: Install and Deploy Docker application 
  hosts: all
  become: true

  tasks:

tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Perform package upgrade (update)
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Install Docker
      apt:
        name: docker.io
        update_cache: yes

    - name: Pull Docker image
      docker_image:
        name: chaddekiran/flask_app
        tag: w1.1

    - name: Run Docker container
      docker_container:
        name: static_flask_app
        image: chaddekiran/flask_app:w1.1
        ports:
          - "80:80" 