on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      BUILD_ID: ${{ github.run_id }}
      JOB_NAME: image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # kiranchadde
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx build -t kiranchadde/${{ JOB_NAME }}:${{ BUILD_ID }} .
          docker push kiranchadde/${{ JOB_NAME }}:${{ BUILD_ID }}
